apiVersion: v1
kind: Pod
metadata:
  name: mypg-pgdump
  namespace: pg-helm
    
spec:
  volumes:
  - name: data
  persistentVolumeClaim:
    claimName: mypg-pgdump

  initContainers:
  - name: chmod
  image: alpine:3
  command: 
    - /bin/sh
    - -c
    - 'chmod 770 /data; chown 1001 /data'
  volumeMounts:
    - name: data
      mountPath: /data

  containers:
  - name: pgdump
  image: vvang/pgdump:0.6
  volumeMounts:
    - name: data
      mountPath: /data
  env:
    - name: WORKDIR
      value: /data
    - name: PGHOST
      value: mypg-postgresql
    - name: PGPORT
      value: '5432'
    - name: PGUSER
      value: postgres
    - name: PGPASSWORD
      valueFrom: 
        secretKeyRef:
          name: mypg-postgresql
          key: postgres-password

